// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8n2JcsBgQV-3aPtMwEvfEHnkszcrHBxQ',
    appId: '1:894474126176:web:deaf8d8fae053938c75405',
    messagingSenderId: '894474126176',
    projectId: 'csc4360-grpproject2-mentalzen',
    authDomain: 'csc4360-grpproject2-mentalzen.firebaseapp.com',
    storageBucket: 'csc4360-grpproject2-mentalzen.firebasestorage.app',
    measurementId: 'G-B9CB9RY4HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAofJcZisf3BPWozbrAfJknotcTBmH7CH0',
    appId: '1:894474126176:android:12e41223759e633ac75405',
    messagingSenderId: '894474126176',
    projectId: 'csc4360-grpproject2-mentalzen',
    storageBucket: 'csc4360-grpproject2-mentalzen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCypKnCt9NBmHgYuGwOLnOSQC9YgvxB2-0',
    appId: '1:894474126176:ios:44e928d0e789c035c75405',
    messagingSenderId: '894474126176',
    projectId: 'csc4360-grpproject2-mentalzen',
    storageBucket: 'csc4360-grpproject2-mentalzen.firebasestorage.app',
    iosBundleId: 'com.nathan2055.mentalzen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCypKnCt9NBmHgYuGwOLnOSQC9YgvxB2-0',
    appId: '1:894474126176:ios:3f5b0cce1782b24bc75405',
    messagingSenderId: '894474126176',
    projectId: 'csc4360-grpproject2-mentalzen',
    storageBucket: 'csc4360-grpproject2-mentalzen.firebasestorage.app',
    iosBundleId: 'com.example.mentalzen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8n2JcsBgQV-3aPtMwEvfEHnkszcrHBxQ',
    appId: '1:894474126176:web:22dc974343e3e060c75405',
    messagingSenderId: '894474126176',
    projectId: 'csc4360-grpproject2-mentalzen',
    authDomain: 'csc4360-grpproject2-mentalzen.firebaseapp.com',
    storageBucket: 'csc4360-grpproject2-mentalzen.firebasestorage.app',
    measurementId: 'G-VNJGRHMFJN',
  );
}